package com.example.demo.entity;

import lombok.Data;

/**
 * @author Green写代码
 * @date 2023-04-21 15:00
 */
@Data
public class SequenceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.name
     *
     * @mbg.generated Sun Nov 18 22:19:38 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.current_value
     *
     * @mbg.generated Sun Nov 18 22:19:38 CST 2018
     */
    private Integer currentValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.step
     *
     * @mbg.generated Sun Nov 18 22:19:38 CST 2018
     */
    private Integer step;
}
